<a href="https://colab.research.google.com/github/c0lbalt/Deep-Learning-w-PyTorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import torch
import numpy as np

# Lists


In [1]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# NumPy Array

In [8]:
np1 = np.random.rand(3,4)
np1

array([[0.26305539, 0.76916338, 0.09767864, 0.62771563],
       [0.93705117, 0.33215787, 0.01549579, 0.03217839],
       [0.42892627, 0.16654824, 0.20766541, 0.35810829]])

In [9]:
np1.dtype

dtype('float64')

# Tensors


In [16]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-2.4460,  0.3841, -0.2423,  1.0634],
        [-1.2306,  1.4575, -0.9625, -0.6511],
        [-0.5297, -1.7741,  0.1776, -0.3195]])

In [17]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [20]:
##Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.2631, 0.7692, 0.0977, 0.6277],
        [0.9371, 0.3322, 0.0155, 0.0322],
        [0.4289, 0.1665, 0.2077, 0.3581]], dtype=torch.float64)